// packages/react/src/components/Tabs/Tabs.tsx
import { forwardRef, useEffect } from 'react'
import { tabs } from '@expandui/core'
import { createClassString } from '@shared/utils'
import useForwardedRef from 'hooks/useForwardedRef'

import type { PolymorphicComponentPropsWithRef, PolymorphicRef } from 'types'

interface Props {
  className?: string
}

export type TabsProps<C extends React.ElementType> =
  PolymorphicComponentPropsWithRef<C, Props>

export const Tabs = forwardRef(
  <C extends React.ElementType = 'div'>(
    { as, className, ...rest }: TabsProps<C>,
    ref?: PolymorphicRef<C>
  ) => {
    const Component = as || 'div'

    const safeRef = useForwardedRef(ref)

    useEffect(() => {
      const containerEl = safeRef?.current
      if (!containerEl || !tabs) return

      tabs.on(containerEl)

      return () => {
        tabs.off(containerEl)
      }
    }, [])

    return (
      <Component
        {...rest}
        ref={safeRef}
        className={createClassString('eui-tabs', className)}
      />
    )
  }
)

Tabs.displayName = 'Tabs'

export default Tabs

// packages/svelte/src/lib/Tabs/Tabs.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { tabs } from '@expandui/core';
  import { createClassString } from '@shared/utils';

  let classProp: string = '';
  export { classProp as class };

  let container: HTMLDivElement

  onMount(() => {
    if (container) tabs.on(container);
  });

  onDestroy(() => {
    if (container ) tabs.off(container);
  });
</script>

<div
  class={
    createClassString(
      'eui-tabs',
      classProp,
    )
  }
  bind:this={container}
  {...$$restProps}
>
  <slot></slot>
</div>
