// packages/react/src/App.tsx
import { Accordion, Button, Modal, Tabs } from './components'

function App() {
  return (
    <>
      <Button.Group>
        <Button>Click me</Button>
      </Button.Group>

      <Accordion>
        <Accordion.Item heading="Heading">Content</Accordion.Item>
        <Accordion.Item heading="Heading">Content</Accordion.Item>
        <Accordion.Item heading="Heading">Content</Accordion.Item>
      </Accordion>

      <Modal.Open modalId="modal-example">Open modal</Modal.Open>
      <Modal id="modal-example" heading="Heading">
        <Modal.Close>Close</Modal.Close>
      </Modal>

      <Tabs>
        <Tabs.List vertical>
          <Tabs.Toggle>One</Tabs.Toggle>
          <Tabs.Toggle>Two</Tabs.Toggle>
          <Tabs.Toggle>Three</Tabs.Toggle>
        </Tabs.List>

        <Tabs.Panel>Content one</Tabs.Panel>
        <Tabs.Panel>Content two</Tabs.Panel>
        <Tabs.Panel>Content three</Tabs.Panel>
      </Tabs>
    </>
  )
}

export default App

// packages/svelte/src/App.svelte
<script lang="ts">
  import {
    Accordion,
    Button,
    Modal,
    Tabs,
  } from './lib'
</script>

<main>
  <Button.Group>
    <Button variant="secondary">
      Click me
    </Button>
  </Button.Group>

  <Accordion>
    <Accordion.Item>
      <Accordion.Button variant="secondary">Title</Accordion.Button>
      <Accordion.Content>Content</Accordion.Content>
    </Accordion.Item>
    <Accordion.Item heading="title">
      Content
    </Accordion.Item>
  </Accordion>

  <Modal.Open modalId="modal">
    Modal
  </Modal.Open>

  <Modal id="modal">
    <Modal.Heading>Title</Modal.Heading>
    <Modal.Content>Content</Modal.Content>
    <Modal.Close>Cancel</Modal.Close>
  </Modal>

  <Tabs>
    <Tabs.List>
      <Tabs.Toggle>One</Tabs.Toggle>
      <Tabs.Toggle>Two</Tabs.Toggle>
      <Tabs.Toggle>Three</Tabs.Toggle>
    </Tabs.List>
    <Tabs.Panel>One content</Tabs.Panel>
    <Tabs.Panel>Two content</Tabs.Panel>
    <Tabs.Panel>Three content</Tabs.Panel>
  </Tabs>
</main>
