// packages/svelte/src/lib/Modal/Modal.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { modal } from '@expandui/core';
  import { createClassString } from '@shared/utils';

  let classProp: string = '';
  export { classProp as class };
  export let forceAction: boolean = false;

  let container: HTMLDivElement

  onMount(() => {
    if (container) modal.on(container);
  });

  onDestroy(() => {
    if (container ) modal.off(container);
  });
</script>

<div
  class={
    createClassString(
      'eui-modal',
      forceAction ? 'force-action' : '',
      classProp,
    )
  }
  bind:this={container}
  {...$$restProps}
>
  <slot></slot>
</div>

// packages/react/src/components/Modal/Modal.tsx
import { forwardRef, useEffect } from 'react'
import { modal } from '@expandui/core'
import { createClassString } from '@shared/utils'
import useForwardedRef from 'hooks/useForwardedRef'

import type { PolymorphicComponentPropsWithRef, PolymorphicRef } from 'types'

interface Props {
  className?: string
  forceAction?: boolean
}

export type ModalProps<C extends React.ElementType> =
  PolymorphicComponentPropsWithRef<C, Props>

export const Modal = forwardRef(
  <C extends React.ElementType = 'div'>(
    { as, className, forceAction, ...rest }: ModalProps<C>,
    ref?: PolymorphicRef<C>
  ) => {
    const Component = as || 'div'

    const safeRef = useForwardedRef(ref)

    useEffect(() => {
      const containerEl = safeRef?.current
      if (!containerEl || !modal) return

      modal.on(containerEl)

      return () => {
        modal.off(containerEl)
      }
    }, [])

    return (
      <Component
        {...rest}
        ref={safeRef}
        className={createClassString(
          'eui-modal',
          forceAction ? 'force-action' : '',
          className ? className : ''
        )}
      />
    )
  }
)

Modal.displayName = 'Modal'

export default Modal
